version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
cache:
 - '%USERPROFILE%\.nuget\packages -> **\project.json'
before_build:
- ps: >-
    nuget restore src
build:
  project: src\xunit.performance.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: bin\**\*.nupkg
