version: 1.0.{build}
os: Visual Studio 2015 - GCE
configuration: Release
before_build:
- ps: >-
    nuget restore src -DisableParallelProcessing
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: bin\**\*.nupkg
