version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
cache:
 - '%USERPROFILE%\.nuget\packages -> **\project.json'
before_build:
- ps: >-
    nuget restore src
build:
  project: src\xunit.performance.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: bin\**\*.nupkg
